version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: invmgt-rabbitmq
    ports:
        - 5673:5672
        - 15673:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - invmgt-network
  app:
    container_name: inventory-mgt-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "4500:4800"
    volumes:
      - ~/inv:/data/app
    networks:
      - invmgt-network
  consumer:
    build:
      context: .
    volumes:
      - .:/src
    depends_on:
      - rabbitmq
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- yarn start:dev'
    environment:
      NODE_ENV: production
      CLOUDAMQP_URL: ${CLOUDAMQP_URL}
    networks:
      - invmgt-network

networks:
  invmgt-network:
    driver: bridge
